/*
 * This source file was generated by the Gradle 'init' task
 */
package de.simon_neutert.map_tile_metrics_cli;

import org.junit.jupiter.api.Test;

import de.simon_neutert.map_tile_metrics_cli.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
